name: tv_browser_example
description: A minimal Flutter app optimized for Android TV (demo).
version: 1.0.0+1
environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true